update http response header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,62 +1,84 @@
 #!/usr/bin/env bash
-# install load balancer
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# colors
-blue='\e[1;34m'
-brown='\e[0;33m'
-green='\e[1;32m'
-reset='\033[0m'
+# uncomment to see the script run in action
+#set -x
 
-echo -e "${blue}Updating and doing some minor checks...${reset}\n"
+echo -e "Updating and doing some minor checks...\n"
 
 function install() {
 	command -v "$1" &> /dev/null
 
 	#shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
-		echo -e "	Installing: ${brown}$1${reset}\n"
+		echo -e "	Installing: $1$\n"
 		sudo apt-get update -y -qq && \
 			sudo apt-get install -y "$1" -qq
 		echo -e "\n"
 	else
-		echo -e "	${green}${1} is already installed.${reset}\n"
+		echo -e "	${1} is already installed.\n"
 	fi
 }
 
-install haproxy #install haproxy
+install nginx #install nginx
 
-echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
 # backup default server config file
-sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
 server_config=\
-"
-defaults
-  mode http
-  timeout client 15s
-  timeout connect 10s
-  timeout server 15s
-  timeout http-request 10s
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-frontend th3gr00t-tech-frontend
-    bind *:80
-    default_backend th3gr00t-tech-backend
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-backend th3gr00t-tech-backend
-    balance roundrobin
-    server 453-web-01 35.243.128.200:80 check
-    server 453-web-02 3.239.120.96:80 check
-"
-
-# shellcheck disable=SC2154
-echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
-
-# enable haproxy to be started by init script
-echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
-
-if [ "$(pgrep -c haproxy)" -le 0 ]; then
-	sudo service haproxy start
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
 else
-	sudo service haproxy restart
+	sudo service nginx restart
 fi
